Added piston control java file
frc5587/Java-Libs pull request #16
Opened 2021-12-01 23:30 UTC by SteepAtticStairs

Added controlling pistons/solenoids in java-libs

2021-12-03 19:17 UTC, JohnnyWobble requested changes

2021-12-03 19:17 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +            doubleSolenoidPistons[i] = new DoubleSolenoid(i, i+1);  // create a new double solenoid
I think `pistonIDs` should be a 2D array, so then each row would represent both ports of the double solenoid. So the array would be 2 by the number of solenoids.

2021-12-03 19:17 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +    public void extend() {  // method to extend the piston(s)
Documentation for a method should be in the javadoc standard. Check this out if you don't know how: https://www.tutorialspoint.com/java/java_documentation.htm

2021-12-03 19:17 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +    public void retract() {  // method to retract the piston(s)
same here

2021-12-03 21:44 UTC, csokolove commented
So the pistonsSet method may have simplified things at the abstract level, but complicated things at the project level. We can look at it - but may just be best to remove it and go back.

2021-12-03 23:40 UTC, JohnnyWobble requested changes

2021-12-03 23:40 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +        for(int i = 0; i < pistonIDS.length; i+=2) {
before this for loop, you should add `doubleSolenoidPistons = new DoubleSolenoid[pistonIDS.length/2];` to initialize the array

2021-12-03 23:40 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +            doubleSolenoidPistons[i] = new DoubleSolenoid(i, i+1);
This shouldn't be `i` and `i + 1`. It should be `pistonIDs[i]` and `pistonIDs[i + 1]`

2021-12-03 23:40 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +        for(int i = 0; i < pistonIDS.length; i+=2) {
you should also make the 2d array, so the for loop doesn't have the `+=2`, cause that causes issues elsewhere

2021-12-03 23:40 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +            doubleSolenoidPistons[i] = new DoubleSolenoid(i, i+1);
the `+=1` will actually cause `doubleSolenoidPistons[i]` to index too far if there is more than 1 piston

2021-12-03 23:40 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +    public void pistonsSet(Value direction) {
I like this! However, you should also include `extend()` and `retract()` methods that just call this method with the correct direction

2021-12-03 23:40 UTC, JohnnyWobble requested changes

2021-12-03 23:40 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +public class PistonControl extends SubsystemBase{
this should also be an abstract class

2021-12-07 02:54 UTC, JohnnyWobble requested changes

2021-12-07 02:54 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +        }
make this call `pistonsSet()`

2021-12-07 02:54 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +        }
Same here

2021-12-07 02:54 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +    public PistonControl(int[][] pistonIDS) {
Give a brief explanation of the purpose of this class and the parameters. To autopopulate the javadoc, type `/**` and a box should appear saying "java docs" or smth, just hit enter

2021-12-07 03:14 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +        for (DoubleSolenoid piston : doubleSolenoidPistons) {
you don't need the for loop

2021-12-07 03:14 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +        for (DoubleSolenoid piston : doubleSolenoidPistons) {
or here

2021-12-07 18:03 UTC, JohnnyWobble requested changes

2021-12-07 18:03 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +            pistonsSet(Value.kForward);
bruh, fix the indents

2021-12-07 18:03 UTC, JohnnyWobble commented on subsystems/PistonControl.java
> +            pistonsSet(Value.kReverse);
and here

2021-12-15 15:24 UTC, JohnnyWobble approved these changes

2021-12-15 15:37 UTC, merged