Add IntakeBase
frc5587/Java-Libs pull request #18
Opened 2021-12-04 20:36 UTC by csokolove

Add abstract IntakeBase utilizing SpeedControllerGroups. `forward()`, `backward()`, `stop()` methods included.

2021-12-04 23:34 UTC, csokolove commented
Addresses request for roller intakes in #7

2021-12-07 03:07 UTC, SteepAtticStairs approved these changes

2021-12-07 17:25 UTC, JohnnyWobble requested changes

2021-12-07 17:25 UTC, JohnnyWobble commented on subsystems/RollerIntakeBase.java
> +            this.freeLimit = freeLimit;
You shouldn't need all these constants, you only use `throttle` and in that case, you can just pass it in, you don't need `IntakeConstants`

2021-12-07 17:25 UTC, JohnnyWobble commented on subsystems/RollerIntakeBase.java
> +        public double throttle;
Removes the unnecessary variables, also make `throttle` protected and not public

2021-12-07 17:25 UTC, JohnnyWobble commented on subsystems/RollerIntakeBase.java
> +            motorGroup = new SpeedControllerGroup(leader, followers);
You really don't need a leader when you use a `SpeedControllerGroup`, just pass them all in together.

2021-12-09 20:51 UTC, csokolove commented
Abstract SimpleMotorBase for use with any motor groups.

2021-12-09 21:32 UTC, Isabel25760 requested changes, later dismissed

2021-12-09 21:32 UTC, Isabel25760 commented on subsystems/SimpleMotorBase.java
> +    configureMotors();
indent this

2021-12-09 21:32 UTC, Isabel25760 commented on subsystems/SimpleMotorBase.java
> +    };
bestie what

2021-12-09 22:39 UTC, csokolove commented on subsystems/SimpleMotorBase.java
> +    };
bestie what;

2021-12-09 22:39 UTC, csokolove commented on subsystems/SimpleMotorBase.java
> +    configureMotors();
indent this

2021-12-09 22:45 UTC, lerminator3 approved these changes
😼

2021-12-10 15:20 UTC, JohnnyWobble requested changes

2021-12-10 15:20 UTC, JohnnyWobble commented on subsystems/SimpleMotorBase.java
> +    public SimpleMotorBase(SpeedController[] motors, double throttle) {
Add some documentation here explaining what this is for, all the other methods are pretty self explainitory

2021-12-15 15:16 UTC, JohnnyWobble submitted a review, later dismissed

2021-12-15 15:16 UTC, JohnnyWobble commented on subsystems/RollerIntakeBase.java
You should delete this file

2021-12-16 02:18 UTC, merged