Adding Ramsete control
frc5587/Java-Libs pull request #21
Opened 2021-12-20 19:13 UTC by JohnnyWobble

This still needs some polishing, but I'm making it now so people can review it

2021-12-20 19:13 UTC, JohnnyWobble commented
I believe this also add some arm stuff cause I merged from there. btw this is the branch that was used at bunnybots

2022-01-12 21:24 UTC, csokolove approved these changes

2022-01-12 21:36 UTC, Isabel25760 requested changes

2022-01-12 21:36 UTC, iscruzrivera commented on auto/AutoPath.java
> +            // I want this to fail hard to people know quickly when something is wrong instead of a NullPointerException down the road
* so. also, please remove any personal pronouns from your documentation

2022-01-12 21:36 UTC, iscruzrivera commented on auto/RamseteCommandWrapper.java
> +            // This "disables" the fancy control from the ramsete controller, allow you to
why isn't this a multi-line comment

2022-01-12 21:36 UTC, iscruzrivera commented on auto/RamseteCommandWrapper.java
> +            // debugging mode is on)
add an enter after this line so it's clear what you're uncommenting and what you're not

2022-01-12 21:36 UTC, Isabel25760 commented on controllers/ArmFPIDController.java
> +    // returns true if Feedforward is enabled
the documentation here should follow java docs convention. you can find a link to that here: https://www.tutorialspoint.com/java/java_documentation.htm
this applies to all of the comments in this file

2022-01-12 21:36 UTC, Isabel25760 commented on controllers/FFController.java
> +    * use this for an elevator, or any FPIDSubsystem that does not require an angle gain
you have a comment here that says to use this for an elevator, but then proceed to have arm methods?

2022-01-12 21:36 UTC, Isabel25760 commented on subsystems/FPIDSubsystem.java
> +        public FPIDConstants(
uhhh why is this formatted onto so many lines

2022-01-12 21:36 UTC, Isabel25760 commented on subsystems/FPIDSubsystem.java
> +        public FPIDConstants(
use the vscode short hand command to clean this file up

2022-01-12 21:36 UTC, Isabel25760 commented on subsystems/FPIDSubsystem.java
> +        // this.enable();
why is this commented out - delete it if it's unecessary

2022-01-12 21:36 UTC, Isabel25760 commented on subsystems/FPIDSubsystem.java
> +    */
add like an empty line between this and the next part to make it clearer

2022-01-12 21:36 UTC, Isabel25760 commented on subsystems/SimpleMotorBase.java
>      public void stop() {
for the line under it, shouldn't it be motorGroup.set(0)?

2022-01-12 23:09 UTC, csokolove commented
I started working on the Javadocs for ArmFPIDController file, but I held it from the last commit only cause there are a couple methods I'm unsure of the exact functionality, so I'm gonna let whoever did those methods finish those docs.

I'll push the documentation I did that I am sure of though

2022-01-24 05:00 UTC, Isabel25760 approved these changes

2022-01-24 05:00 UTC, iscruzrivera commented on auto/AutoPath.java
> +            // Fail hard to people know quickly when something is wrong instead of a NullPointerException down the road
* so

2022-01-24 05:00 UTC, iscruzrivera commented on controllers/ArmFPIDController.java
> +    // params fpid are Feedforward and PID gains, param sCosVA is an array of the ks, kcos, kv, and ka used by an ArmFeedForward
this stuff should be javadocs too

2022-01-24 17:57 UTC, Isabel25760 approved these changes

2022-01-24 17:57 UTC, merged